<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<!doctype html>
<html>
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1"/>
    <link rel="stylesheet" type="text/css" href="<?php /* @escapeNotVerified */ echo $this->getAssetUrl('ShopGo_Locker::css/style-locker.css') ?>" />
    <link href='https://fonts.googleapis.com/css?family=Roboto:400,300' rel='stylesheet' type='text/css'>
</head>
<body>
    <h1 class="logo">
        <img src="<?php /* @escapeNotVerified */ echo $this->getAssetUrl('ShopGo_Locker::images/shopgo-logo.svg') ?>" />
    </h1>
    <div class="content">
        <h1 class="title"><?php echo __("This website is currently inaccessible."); ?></h1>
        <span class="title-info"><?php echo __("If you are the owner of this website, please <a href=\"mailto:support@shopgo.me\" >contact our support</a>."); ?></span>
    </div>
    <footer class="footer">
        <span class="footer-info"><a href="http://www.shopgo.me/">www.shopgo.me</a></span>
    </footer>
</body>
</html>